# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PZJBleManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PZJBleManager
   pod 'SVProgressHUD', '~> 2.2.5'

  target 'PZJBleManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PZJBleManagerUITests' do
    # Pods for testing
  end

end
